### ISSUE TITLE
New editor roadmap

### ISSUE THREAD

**Issue by wildlifehexagon** [dictyBase/dicty-components-page-editor#737]
**Marks**
- [x] Bold
- [x] Italic
- [x] Underline
- [x] Strikethrough
- [x] Subscript
- [x] Superscript

**Blocks**
- [x] H1
- [x] H2
- [x] H3
- [x] Left align
- [x] Right align
- [x] Center align
- [x] Justify align
- [x] Divider
- [x] Line spacing
- [x] Images (external)
- [x] Video embed
- [ ] Ordered list
- [ ] Unordered list
- [ ] Increase indent (for lists)
- [ ] Decrease indent (for lists)
- [ ] Tables
- [ ] Image upload
- [ ] Video upload

**Inline**
- [x] Links

**Fonts**
- [x] Font color
- [x] Font size
- [x] Font family

**New Features**
- [ ] Scientific symbols #4

**Misc**
- [x] Tooltips on buttons
- [x] Buttons show active state
- [x] Undo/redo functionality
