### ISSUE TITLE
Add tables

### ISSUE THREAD

**Issue by wildlifehexagon** [dictyBase/dicty-components-page-editor#792]
Needed features:

- [ ] Add table width / size dictyBase/dicty-frontpage#121 
- [ ] Change column width to make asymmetric table dictyBase/dicty-frontpage#124 
- [ ] Allow table lines to be white or invisible dictyBase/dicty-frontpage#129 https://github.com/dictyBase/dicty-components-page-editor/issues/758

**Comment by wildlifehexagon** [comment]
Initial implementation has been added. Still need to add the above features + clean up the UI of the toolbar. The insert/delete rows/columns buttons should only be visible if the current selection is inside a table. We should also have a modal to let the user specify the border color.

Tests still need to be included.

**Comment by wildlifehexagon** [comment]
The UI for the toolbar table buttons is cleaned up. However, the requested features still need to be added.
