### ISSUE TITLE
Table plugin enhancements

### ISSUE THREAD

**Issue by wildlifehexagon** [dictyBase/dicty-components-page-editor#8]
Putting all table plugin requests into one issue.

- [ ] Add table width / size dictyBase/dicty-frontpage#121 
- [ ] Change column width to make asymmetric table dictyBase/dicty-frontpage#124 
- [ ] Allow table lines to be white or invisible dictyBase/dicty-frontpage#129 

Something to consider: adding a new grid plugin that utilizes Material-UI's `Grid` component. This would allow for flexible and responsive layouts within the page. This would also help with dictyBase/dicty-components-page-editor#2, improving the behavior of images.
